### PR TITLE
validating date and period

### PR DESCRIPTION
**Pull request by rednaks**
I'm not sure if this is want you had in mind also I'm not an expert of momentjs so if anyone can review this :)

EDIT: I also changed the name of the function `isPeriod` to `isValidPeriod` .

### CODE REVIEW

**Comment by aymen-mouelhi** [comment]
@rednaks 👍 
One remark, maybe we should add a method: isInFuture ?
a valid start date for us: is a valid moment date + a date that occurs in the future

**Comment by rednaks** [comment]
Yes, you're right, we have to check that also.
The future is starting from `now` I guess ?

Hold this PR open I will add it now :)

**Comment by aymen-mouelhi** [comment]
cool, thanks @rednaks !

**Comment by aymen-mouelhi** [comment]
btw, you can test the slack command now in slack
/book

**Comment by rednaks** [comment]
I think also we should change `isValid` to `isValidDate` the `Utils/utils.js` file is more general and may containt some helpers than date related right ?

**Comment by aymen-mouelhi** [comment]
yepp 👍 
Feel free skan :)

**Pull request merged**
